_prefs: 
  mapid: ''
  saveCenter: true
_properties: {}
attribution: ''
bounds: 
  - -180
  - -85.0511
  - 180
  - 85.0511
center: 
  - -70.8398
  - 37.9962
  - 2
description: ''
format: "png8:m=h"
interactivity_layer: ''
layers: null
maxzoom: 14
minzoom: 0
name: ''
source: "mapbox:///mapbox.mapbox-streets-v5"
styles: 
  - style.mss
template: ''
