_prefs: 
  mapid: ''
  saveCenter: true
_properties: {}
attribution: ''
bounds: 
  - -180
  - -85.0511
  - 180
  - 85.0511
center: 
  - -81.7383
  - 27.3718
  - 3
description: ''
format: "png8:m=h"
interactivity_layer: ''
layers: null
maxzoom: 14
minzoom: 0
name: ''
source: "mapbox:///mapbox.mapbox-streets-v5"
styles: 
  - style.mss
  - labels.mss
  - landuse.mss
template: ''
