_prefs: 
  mapid: katiekowalsky.236692c1
  saveCenter: false
_properties: {}
attribution: ''
bounds: 
  - -180
  - -85.0511
  - 180
  - 85.0511
center: 
  - -77.6953
  - 41.7057
  - 4
description: ''
format: "png8:m=h"
interactivity_layer: ''
layers: null
maxzoom: 22
minzoom: 0
name: lichtenstein
source: "mapbox:///mapbox.mapbox-terrain-v1,mapbox.mapbox-streets-v5"
styles: 
  - style.mss
  - labels.mss
  - roads.mss
  - landuse.mss
template: ''
